test: set exit code to 0 to get invalid args tests to pass (#316)
Currently the CI on the main branch is red because non-zero exit code has started to be considered as test failure since Deno 1.44.0. 

```
ERRORS 

parseArgsForLogSubcommand ... specify invalid format in since => ./src/subcommands/logs_test.ts:51:11
error: Error: Test case finished with exit code set to 1.
  await t.step("specify invalid format in since", () => {
  ^
    at exitSanitizer (ext:cli/40_test.js:113:15)
    at async Object.outerWrapped [as fn] (ext:cli/40_test.js:134:14)
    at async TestContext.step (ext:cli/40_test.js:492:22)
    at async file:///Users/runner/work/deployctl/deployctl/src/subcommands/logs_test.ts:51:3

parseArgsForLogSubcommand ... specify invalid format in until => ./src/subcommands/logs_test.ts:55:11
error: Error: Test case finished with exit code set to 1.
  await t.step("specify invalid format in until", () => {
  ^
    at exitSanitizer (ext:cli/40_test.js:113:15)
    at async Object.outerWrapped [as fn] (ext:cli/40_test.js:134:14)
    at async TestContext.step (ext:cli/40_test.js:492:22)
    at async file:///Users/runner/work/deployctl/deployctl/src/subcommands/logs_test.ts:55:3

 FAILURES 
```

This commit works around this issue by forcibly setting exit code to 0.